[2019-12-28 13:06:07] ERROR 7632:[taskWidgetImpl.py:62] - can't compare datetime.datetime to datetime.date
[2019-12-28 13:07:20] ERROR 19864:[taskWidgetImpl.py:62] - an integer is required (got type datetime.datetime)
[2019-12-28 14:44:39] ERROR 8808:[taskWidgetImpl.py:62] - an integer is required (got type datetime.datetime)
[2019-12-28 14:45:01] ERROR 4060:[taskWidgetImpl.py:62] - an integer is required (got type datetime.datetime)
[2019-12-28 15:02:21] ERROR 3204:[loadData.py:51] - no such column: ？
[2019-12-28 18:15:50] ERROR 22340:[loadData.py:51] - Incorrect number of bindings supplied. The current statement uses 5, and there are 4 supplied.
[2019-12-28 18:15:52] ERROR 22340:[taskWidgetImpl.py:70] - Incorrect number of bindings supplied. The current statement uses 5, and there are 4 supplied.
[2019-12-28 21:38:29] ERROR 23524:[taskWidgetImpl.py:149] - list index out of range
[2019-12-28 21:41:47] ERROR 23500:[loadData.py:51] - no such column: is_date
[2019-12-28 21:41:50] ERROR 23500:[taskWidgetImpl.py:151] - no such column: is_date
[2019-12-28 21:43:03] ERROR 13884:[taskWidgetImpl.py:91] - 'is_finish'
[2019-12-28 21:45:02] ERROR 5980:[taskWidgetImpl.py:91] - 'is_finish'
[2019-12-28 21:47:25] ERROR 19288:[taskWidgetImpl.py:91] - 'is_finish'
[2019-12-28 21:48:04] ERROR 21604:[taskWidgetImpl.py:91] - no such column: tbt.is_dated，tbt.is_finish
[2019-12-28 21:48:25] ERROR 12212:[taskWidgetImpl.py:91] - 'task_desc'
[2019-12-28 22:14:06] ERROR 22196:[loadData.py:51] - near ")": syntax error
[2019-12-28 22:14:07] ERROR 22196:[taskWidgetImpl.py:167] - near ")": syntax error
[2019-12-28 22:14:22] ERROR 22724:[loadData.py:51] - no such column: is_date
[2019-12-28 22:14:25] ERROR 22724:[taskWidgetImpl.py:167] - no such column: is_date
[2019-12-28 22:26:46] ERROR 528:[loadData.py:51] - near "vadlues": syntax error
[2019-12-28 22:26:48] ERROR 528:[taskWidgetImpl.py:168] - near "vadlues": syntax error
[2019-12-28 22:27:08] ERROR 7068:[loadData.py:51] - no such column: is_date
[2019-12-28 22:27:09] ERROR 7068:[taskWidgetImpl.py:168] - no such column: is_date
